name: chalkdart
description: Console/Logging text coloring and styling library for Dart. 'Terminal string styling done right'
             The default mode uses ANSI codes to style the text for Console/Terminal display.
             HTML mode can be activated so that all text is colored and styled using HTML so ChalkDart
             can be use for sending colored/styled logs to the Server for viewing from a browser as well.
version: 3.0.6
homepage: https://github.com/timmaffett/chalkdart
screenshots:
  - description: 'vscode debug terminal example'
    path: media/ABasic.png
  - description: 'windows terminal example'
    path: media/AChalkDart2.png
  - description: '256 color chart from chalkdart_example.dart output to windows terminal'
    path: media/Ansi0.png
  - description: 'Full color chart from chalkdart_example.dart output to windows terminal'
    path: media/AWindowsTerminal.png

topics:
  - cli
  - color
  - coloring
  - ansi
  - html

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  args: ^2.3.1
  lints: ^5.1.1
  test: ^1.29.0